packageExtensions:
  "@upsetjs/react@*":
    peerDependencies:
      react-refresh: "*"
  # "@vue/cli-service@*":
  #   peerDependencies:
  #     "@vue/cli-plugin-eslint": "*"
  #     "@vue/cli-plugin-typescript": "*"
  # babel-preset-react-app@*:
  #   dependencies:
  #     "@babel/plugin-proposal-private-property-in-object": "*"
  # eslint-config-airbnb-typescript@*:
  #   dependencies:
  #     eslint-config-airbnb-base: "*"
  # eslint-module-utils@*:
  #   dependencies:
  #     eslint-import-resolver-node: "*"
  # fork-ts-checker-webpack-plugin@*:
  #   dependencies:
  #     vue-template-compiler: "*"
  # jss-plugin-rule-value-function@*:
  #   dependencies:
  #     tiny-warning: "*"
  # postcss-loader@*:
  #   dependencies:
  #     postcss: "*"
  # prism-react-renderer@*:
  #   dependencies:
  #     react: "*"
  # react-live@*:
  #   dependencies:
  #     "@philpl/buble": "*"
  #     react: "*"
  # react-simple-code-editor@*:
  #   dependencies:
  #     react: "*"
  # react-vega@*:
  #   dependencies:
  #     prop-types: "*"
  # typedoc@*:
  #   dependencies:
  #     shiki-themes: "*"
  vega-embed@*:
    dependencies:
      vega-util: "*"
  vega-lite@*:
    dependencies:
      vega-typings: "*"
  vega-tooltip@*:
    dependencies:
      vega-typings: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
